Repository clio-lang/clio, pull requests merged in 2020-01, with the labels that each got.

#97 Port `deps add` from 0.1.6
  .gitignore
  cli/commands/build.js
  cli/commands/deps.js
  cli/commands/deps_commands/add.js
  cli/commands/deps_commands/get.js
  cli/commands/index.js
  cli/commands/init.js
  cli/commands/new.js
  cli/commands/run.js
  cli/commands/tests/build.test.js
  cli/commands/tests/init.test.js
  cli/commands/tests/new.test.js
  package-lock.json
  package.json
  package/config.js
  package/dependencies.js
  package/index.js
  package/npm_dependencies.js
  package/packageConfig.js
  package/tests/packageConfig.test.js
Labels: enhancement

#111 Rename browser target to web
  cli/commands/new.js
  cli/commands/tests/build.test.js
Labels: bug

#112 Fix coveralls check
  .github/workflows/push-checks.yml
  package.json
Labels: bug

#122 Update Coveralls Badge branch
  readme.md
Labels: enhancement

#123 Fix misleading success message
  cli/commands/new.js
Labels: Area: CLI

#125 Parallel coverage calculation
  .github/workflows/push-checks.yml
Labels: enhancement

#129 Fix ugly build errors
  cli/commands/build.js
  cli/commands/tests/build.test.js
  cli/lib/colors.js
  cli/lib/tests/colors.test.js
Labels: Area: CLI, enhancement

#138 Add PR template
  .github/pull_request_template.md
Labels: Idea

#141 Move jest configuration to jest.config.js
  jest.config.js
  package.json
Labels: Idea, enhancement

#142 Fix "Error: undefined" message
  cli/lib/colors.js
  cli/lib/tests/colors.test.js
  packages/internals/src/scope.js
Labels: Area: CLI, bug

#147 Minor Docs adjustments
  docs/SUMMARY.md
  docs/clio-executable/README.md
  docs/clio-executable/clio-ast.md
  docs/clio-executable/clio-compile.md
  docs/clio-executable/clio-completion.md
  docs/clio-executable/clio-deps.md
  docs/clio-executable/clio-highlight.md
  docs/clio-executable/clio-host.md
  docs/clio-executable/clio-init.md
  docs/clio-executable/clio-new.md
  docs/clio-executable/clio-run.md
  docs/learn/official-tutorial/flow.md
  docs/learn/official-tutorial/hosting.md
  docs/learn/official-tutorial/modules.md
  docs/modules/README.md
  docs/modules/browser.md
  docs/modules/clio-environment.md
  docs/modules/clio-modules.md
  docs/modules/js-modules.md
  docs/quick.html
Labels: enhancement
